// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/useurmind/certbird/k8s-controller/pkg/apis/cr/v1"
	scheme "github.com/useurmind/certbird/k8s-controller/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CertRequestsGetter has a method to return a CertRequestInterface.
// A group's client should implement this interface.
type CertRequestsGetter interface {
	CertRequests(namespace string) CertRequestInterface
}

// CertRequestInterface has methods to work with CertRequest resources.
type CertRequestInterface interface {
	Create(ctx context.Context, certRequest *v1.CertRequest, opts metav1.CreateOptions) (*v1.CertRequest, error)
	Update(ctx context.Context, certRequest *v1.CertRequest, opts metav1.UpdateOptions) (*v1.CertRequest, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.CertRequest, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.CertRequestList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.CertRequest, err error)
	CertRequestExpansion
}

// certRequests implements CertRequestInterface
type certRequests struct {
	client rest.Interface
	ns     string
}

// newCertRequests returns a CertRequests
func newCertRequests(c *CertbirdV1Client, namespace string) *certRequests {
	return &certRequests{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the certRequest, and returns the corresponding certRequest object, and an error if there is any.
func (c *certRequests) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.CertRequest, err error) {
	result = &v1.CertRequest{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("certrequests").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CertRequests that match those selectors.
func (c *certRequests) List(ctx context.Context, opts metav1.ListOptions) (result *v1.CertRequestList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.CertRequestList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("certrequests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested certRequests.
func (c *certRequests) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("certrequests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a certRequest and creates it.  Returns the server's representation of the certRequest, and an error, if there is any.
func (c *certRequests) Create(ctx context.Context, certRequest *v1.CertRequest, opts metav1.CreateOptions) (result *v1.CertRequest, err error) {
	result = &v1.CertRequest{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("certrequests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(certRequest).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a certRequest and updates it. Returns the server's representation of the certRequest, and an error, if there is any.
func (c *certRequests) Update(ctx context.Context, certRequest *v1.CertRequest, opts metav1.UpdateOptions) (result *v1.CertRequest, err error) {
	result = &v1.CertRequest{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("certrequests").
		Name(certRequest.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(certRequest).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the certRequest and deletes it. Returns an error if one occurs.
func (c *certRequests) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("certrequests").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *certRequests) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("certrequests").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched certRequest.
func (c *certRequests) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.CertRequest, err error) {
	result = &v1.CertRequest{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("certrequests").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
