// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/useurmind/certbird/k8s-controller/pkg/client/clientset/versioned/typed/cr/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeCertbirdV1 struct {
	*testing.Fake
}

func (c *FakeCertbirdV1) CertRequests(namespace string) v1.CertRequestInterface {
	return &FakeCertRequests{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeCertbirdV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
