// Code generated by lister-gen. DO NOT EDIT.

package v1

// CertRequestListerExpansion allows custom methods to be added to
// CertRequestLister.
type CertRequestListerExpansion interface{}

// CertRequestNamespaceListerExpansion allows custom methods to be added to
// CertRequestNamespaceLister.
type CertRequestNamespaceListerExpansion interface{}
