// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	crv1 "github.com/useurmind/certbird/k8s-controller/pkg/apis/cr/v1"
	versioned "github.com/useurmind/certbird/k8s-controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/useurmind/certbird/k8s-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/useurmind/certbird/k8s-controller/pkg/client/listers/cr/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CertRequestInformer provides access to a shared informer and lister for
// CertRequests.
type CertRequestInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.CertRequestLister
}

type certRequestInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCertRequestInformer constructs a new informer for CertRequest type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCertRequestInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCertRequestInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCertRequestInformer constructs a new informer for CertRequest type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCertRequestInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CertbirdV1().CertRequests(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CertbirdV1().CertRequests(namespace).Watch(context.TODO(), options)
			},
		},
		&crv1.CertRequest{},
		resyncPeriod,
		indexers,
	)
}

func (f *certRequestInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCertRequestInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *certRequestInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&crv1.CertRequest{}, f.defaultInformer)
}

func (f *certRequestInformer) Lister() v1.CertRequestLister {
	return v1.NewCertRequestLister(f.Informer().GetIndexer())
}
