// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/useurmind/certbird/k8s-controller/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// CertRequests returns a CertRequestInformer.
	CertRequests() CertRequestInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// CertRequests returns a CertRequestInformer.
func (v *version) CertRequests() CertRequestInformer {
	return &certRequestInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
